name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Display Xcode Version
        run: xcodebuild -version

      - name: Display Swift Version
        run: swift --version

      - name: Build
        run: swift build

      - name: Run Tests
        run: swift test
